### ISSUE TITLE
Home page background is not fit in Redmi note 3

### ISSUE THREAD

**Issue by tushar821999** [tushar821999/Abusive-Word-Remover-API#2]
Path of that file : 

Templates -> index.html
![whatsapp image 2018-11-23 at 9 39 27 am](https://user-images.githubusercontent.com/30934449/48928390-5df44f80-ef04-11e8-84f7-0d8b622882be.jpeg)

**Comment by rishabh307** [comment]
body, html {

  height: 100%;
}
.bg {
  /* The image used */
  background-image: url("/static/back.jpg");

  /* Full height */
  height: 100%;

  /* Center and scale the image nicely */
  background-position: center;
  background-repeat: no-repeat;
  background-size: cover;
}

#In Html File ( Path: Templates/index.html ):
<div class="bg"><div align=center><a href='https://www.counter12.com'><img src='https://www.counter12.com/img-ZwCZcZ211Z45Byz5-9.gif' border='0' alt='counter'></a><script type='text/javascript' src='https://www.counter12.com/ad.js?id=ZwCZcZ211Z45Byz5'></script></div>
  <div class="container">
      <img src="/static/banned.png" class="avatar">
          <h1>Abusive Word Remover</h1>
          <form action="{{url_for('filtered')}}" method="get">
              <p id="Paragraph">Enter Paragraph Here</p>
              <input type="text" name="inputpara" placeholder="Input Paragraph" id="field">
              <input type="submit" name="" value="Filter  It" id="button" onclick="change()">
          </form>
            <center>
                <p>Beta 1.0.0</p>
            <a href="https://github.com/tushar821999/Abusive-Word-Remover-API">Want to contribute?</a><br><br>
          </center>
      </div>


</div>

This Might Solve Your Problem

**Comment by rishabh307** [comment]
# Update Templates/index.html file with this code
`In Style Tag : 
body, html {

  height: 100%;
}
.bg {
  /* The image used */
  background-image: url("/static/back.jpg");

  /* Full height */
  height: 100%;

  /* Center and scale the image nicely */
  background-position: center;
  background-repeat: no-repeat;
  background-size: cover;
}

In Body Tag Add a div tag with class "bg"

This might solve your problem

**Comment by tushar821999** [comment]
Yes Its Working
