### ISSUE TITLE
Having problem in detection of 'modified' Abusive Words

### ISSUE THREAD

**Issue by Shivaansh-Agarwal** [tushar821999/Abusive-Word-Remover-API#3]
If we modify some words in the actual Abusive Word, then it is not working.
![1](https://user-images.githubusercontent.com/29867531/49565806-74f86000-f94e-11e8-878c-0250a29bada1.PNG)
![2](https://user-images.githubusercontent.com/29867531/49565859-affa9380-f94e-11e8-849a-2a48e906666d.PNG)
Hope you'll find a solution soon.

**Comment by tushar821999** [comment]
Thanks For Finding Bug We will try to solve asap

**Comment by Shashank-Mittal** [comment]
it can be solved with the help of Regular Expression module
`import re`
`for i in words:`
            `i=re.sub('[^a-zA-Z]',"",i)`
            `i=i.lower()`

**Comment by tushar821999** [comment]
Pull Request Under Review

**Comment by tushar821999** [comment]
Pull Request Accepted @Shashank-Mittal and issue is solved @shiv-1998
